version: '3.2'
services:
    web:
        build:
            context: .
        restart: unless-stopped
        external_links:
            - postgres
        ports:
            - "8001:8001"
        command: "daphne teachbeach.asgi:application -b 0.0.0.0 -p 8001"
        volumes:
            - .:/home/docker/code
            - type: bind
              source: ${IMAGE_DIR}
              target: /home/docker/code/media/uploads
        env_file:
            - .env
        # environment:
        #     - DJANGO_SETTINGS_MODULE=local_settings
        container_name: teachbeach_web_dev
        # links:
        #     - redis

    redis:
        image: redis:alpine
        ports:
        - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass Ygd445dklI_nVs45gbsqeeju7Tf
        volumes:
        - 'redisdata:/data'
        container_name: teachbeach_redis

networks:
  default:
    external:
      name: teachbeach_default
volumes:
    redisdata:
