# Generated by Django 2.1.5 on 2019-01-20 16:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('uniqueness', models.TextField(blank=True, null=True)),
                ('teacher_supplies', models.TextField(blank=True, null=True)),
                ('students_bring', models.TextField(blank=True, null=True)),
                ('what_else', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('experience', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='begginer', max_length=100)),
                ('teacher_background', models.TextField()),
                ('teacher_media', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('accomplishments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lesson_length', models.IntegerField()),
                ('number_of_lessons', models.IntegerField()),
                ('class_type', models.CharField(choices=[('online', 'online'), ('address', 'address'), ('select', 'select')], default='online', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('parking', models.CharField(max_length=100)),
                ('other_services', models.TextField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_hours', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
        migrations.AddField(
            model_name='class',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Venue'),
        ),
    ]
