# Generated by Django 2.1.5 on 2019-01-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190120_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='category',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subcategory_text',
        ),
    ]
