# Generated by Django 2.1.5 on 2019-02-06 08:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190128_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='accomplishments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='lesson_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='number_of_lessons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_background',
            field=models.TextField(null=True),
        ),
    ]
