# Generated by Django 2.1.5 on 2019-02-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190206_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='user_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
        migrations.AddField(
            model_name='class',
            name='user_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SubCategory'),
        ),
    ]
