# Generated by Django 2.1.5 on 2019-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='headline',
        ),
        migrations.AddField(
            model_name='class',
            name='group_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
