# Generated by Django 2.1.5 on 2019-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190206_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='experience',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=100, null=True),
        ),
    ]
