# Generated by Django 2.1.5 on 2019-02-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190207_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='address_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='address_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='address_zip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
