# Generated by Django 2.1.5 on 2019-02-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190211_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group_lesson_length',
            field=models.IntegerField(null=True),
        ),
    ]
