# Generated by Django 2.1.5 on 2019-02-12 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_class_group_lesson_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='accomplishments',
        ),
        migrations.RemoveField(
            model_name='class',
            name='lesson_length',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher_background',
        ),
        migrations.RemoveField(
            model_name='class',
            name='uniqueness',
        ),
        migrations.AddField(
            model_name='class',
            name='instant_booking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='private_lesson_length',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule_from',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule_to',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
