# Generated by Django 2.1.5 on 2019-02-13 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190213_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
        migrations.RemoveField(
            model_name='class',
            name='media',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
