# Generated by Django 2.1.5 on 2019-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190213_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='experience',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('online', 'online'), ('address', 'address'), ('venue', 'venue'), ('student_location', 'student_location'), ('custom', 'custom')], default='online', max_length=100),
        ),
    ]
