# Generated by Django 2.1.5 on 2019-02-15 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190215_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=100), null=True, size=10),
        ),
    ]
