# Generated by Django 2.1.5 on 2019-02-19 13:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_class_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='schedule_excluded',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='class',
            name='weekdays_schedule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
