# Generated by Django 2.1.5 on 2019-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190219_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
