# Generated by Django 2.1.5 on 2019-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_class_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='day_select_type',
            field=models.TextField(null=True),
        ),
    ]
