# Generated by Django 2.1.5 on 2019-02-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_class_day_select_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='number_of_lessons',
            new_name='group_number_of_lessons',
        ),
    ]
