# Generated by Django 2.1.5 on 2019-02-22 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190222_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='private_number_of_lessons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10),
        ),
    ]
