# Generated by Django 2.1.5 on 2019-02-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_class_group_number_of_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLearner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts', models.BooleanField(default=False)),
                ('email', models.TextField(null=True)),
                ('first_name', models.TextField(null=True)),
                ('learnerNeeds', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
            ],
        ),
    ]
