# Generated by Django 2.1.5 on 2019-03-03 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190223_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='flexible_dates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='until_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='areas_of_specialty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=10),
        ),
    ]
