# Generated by Django 2.1.5 on 2019-03-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190311_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='group_packages',
            new_name='custom_packages',
        ),
    ]
