# Generated by Django 2.1.5 on 2019-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190311_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='location_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='private_className',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='private_class_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='teaching_country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
