# Generated by Django 2.1.5 on 2019-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190315_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
