# Generated by Django 2.1.5 on 2019-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_class_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='drop_in_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
