# Generated by Django 2.1.5 on 2019-04-01 20:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_class_drop_in_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
        ),
    ]
