# Generated by Django 2.1.5 on 2019-04-07 20:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_globalpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalpackage',
            name='packages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
