# Generated by Django 2.1.5 on 2019-04-22 17:28

from django.db import migrations


def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for c in Class.objects.all():
        if not c.currency:
            c.currency = 'usd'
        if not c.start_date:
            c.start_date = "2019-04-01"
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190407_2043'),
    ]

    operations = [
        migrations.RunPython(update_classes),
    ]
