# Generated by Django 2.1.5 on 2019-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190422_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='groupClassSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='maxSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
