# Generated by Django 2.1.5 on 2019-05-17 11:07

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190503_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='classlearner',
            name='session_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='classlearner',
            name='status',
            field=models.CharField(default='wait_payment', max_length=100),
        ),
        migrations.AddField(
            model_name='classlearner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Any', 'Any')], max_length=100), blank=True, null=True, size=10),
        ),
    ]
