# Generated by Django 2.1.5 on 2019-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190517_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='address_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
