# Generated by Django 2.1.5 on 2019-04-22 17:28

from django.db import migrations


def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for c in Class.objects.all():
        if c.address_city == 'South Pasadena':
            c.address_state = 'CA'
        if c.address_city == 'Chacala':
            c.address_state = 'Nay.'
        if c.address_city == 'Portland':
            c.address_state = 'ME'
        if c.address_city == 'West borough':
            c.address_state = 'PA'
        if c.address_city == 'St. Petersburg':
            c.address_state = 'FL'
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_class_address_state'),
    ]

    operations = [
        migrations.RunPython(update_classes),
    ]
