# Generated by Django 2.1.5 on 2019-04-22 17:28

from django.db import migrations

def backward(apps, schema_editor):
    pass

def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for c in Class.objects.all():
        if c.address_city == 'West borough':
            c.address_state = 'PA'
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20190525_1451'),
    ]

    operations = [
        migrations.RunPython(update_classes),
        migrations.RunPython(backward),
    ]
