# Generated by Django 2.1.5 on 2019-06-05 14:53

from django.db import migrations

def backward(apps, schema_editor):
    pass

def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for c in Class.objects.all():
        # scheduleDates: [{date: "2019-06-04", start: "12:54", end: "14:58"},…
        if c.schedule_dates and type(c.schedule_dates[0]) == str:
            c.schedule_dates = []
            # c.scheduleDates = [dict(
            #     date=x,
            #     start=c.schedule_from,
            #     end=c.schedule_to,
            # ) for x in c.scheduleDates]
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20190525_1509'),
    ]

    operations = [
        migrations.RunPython(update_classes),
        migrations.RunPython(backward),
    ]
