# Generated by Django 2.1.5 on 2019-06-05 17:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20190605_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
