# Generated by Django 2.1.5 on 2019-06-05 17:10

from django.db import migrations
from django.contrib.gis.geos import Point


def backward(apps, schema_editor):
    pass

def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for c in Class.objects.all():
        if c.lat is not None:
            c.point = Point(x=c.lng, y=c.lat, srid=4326)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_class_point'),
    ]

    operations = [
        migrations.RunPython(update_classes),
        migrations.RunPython(backward),
    ]
