# Generated by Django 2.1.5 on 2019-06-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190605_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='schedule_dates',
        ),
    ]
