# Generated by Django 2.1.5 on 2019-06-05 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_class_schedule_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='schedule_dates',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
