# Generated by Django 2.1.5 on 2019-06-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_privateenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('time_from', models.TextField()),
                ('time_to', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClassLearner')),
            ],
        ),
    ]
