# Generated by Django 2.1.5 on 2019-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_groupenroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupenroll',
            name='status',
            field=models.TextField(default='approved'),
        ),
        migrations.AddField(
            model_name='privateenroll',
            name='status',
            field=models.TextField(default='requested'),
        ),
    ]
