# Generated by Django 2.1.5 on 2019-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20190624_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='reserved_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
