# Generated by Django 2.1.5 on 2019-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_classlearner_reserved_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='alerts',
            field=models.BooleanField(default=False),
        ),
    ]
