# Generated by Django 2.1.5 on 2019-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_teacher_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='stripe_account_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
