# Generated by Django 2.1.5 on 2019-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_usercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('online', 'online'), ('address', 'address'), ('venue', 'venue'), ('student_location', 'student_location'), ('custom', 'custom'), ('other', 'other')], default='online', max_length=100),
        ),
    ]
