# Generated by Django 2.1.5 on 2019-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20190729_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupenroll',
            name='time_from_gmt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='privateenroll',
            name='time_from_gmt',
            field=models.DateTimeField(null=True),
        ),
    ]
