# Generated by Django 2.1.5 on 2019-08-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20190802_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupenroll',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateenroll',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
