# Generated by Django 2.1.5 on 2019-08-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateenroll',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
