# Generated by Django 2.1.5 on 2019-08-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20190809_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
