# Generated by Django 2.1.5 on 2019-08-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_class_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlearner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='classlearner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='classlearner',
            name='phone',
        ),
    ]
