# Generated by Django 2.1.5 on 2019-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20190812_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
