# Generated by Django 2.1.5 on 2019-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_classlearner_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlearner',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
