# Generated by Django 2.1.5 on 2019-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20190812_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='num_lessons',
            field=models.IntegerField(default=1),
        ),
    ]
