# Generated by Django 2.1.5 on 2019-09-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_class_class_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
