# Generated by Django 2.1.5 on 2019-09-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_usercard_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='brand',
            field=models.CharField(default='Visa', max_length=100),
            preserve_default=False,
        ),
    ]
