# Generated by Django 2.1.5 on 2019-09-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_usercard_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercard',
            old_name='token',
            new_name='customer_id',
        ),
    ]
