# Generated by Django 2.1.5 on 2019-09-12 10:43

from django.db import migrations

def backward(apps, schema_editor):
    pass

def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for x in Class.objects.all():
        if not x.timezone:
            x.timezone = 'America/Mazatlan'
            x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20190911_1916'),
    ]

    operations = [
        migrations.RunPython(update_classes, backward),
    ]
