# Generated by Django 2.1.5 on 2019-09-12 16:15

from django.db import migrations


def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    UserCard = apps.get_model('main', 'UserCard')
    UserCard.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20190912_1043'),
    ]

    operations = [
        migrations.RunPython(update_classes),
    ]
