# Generated by Django 2.1.5 on 2019-09-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20190912_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
