# Generated by Django 2.1.5 on 2019-09-19 11:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_class_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subcategories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=3),
        ),
    ]
