# Generated by Django 2.1.5 on 2019-09-19 11:41

from django.db import migrations


def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for x in Class.objects.all():
        if x.user_subcategory:
            x.subcategories = [x.user_subcategory.pk, ]
            x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_class_subcategories'),
    ]

    operations = [
        migrations.RunPython(update_classes),
    ]
