# Generated by Django 2.1.5 on 2019-09-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_user_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
