# Generated by Django 2.1.5 on 2019-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
