# Generated by Django 2.1.5 on 2019-09-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_user_stripe_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
