# Generated by Django 2.1.5 on 2019-09-23 14:48

from django.db import migrations


def update_teachers(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Teacher = apps.get_model('main', 'Teacher')
    for x in Teacher.objects.all():
        if x.user and not x.user.is_company:
            x.first_name = x.user.first_name
            x.last_name = x.user.last_name
            x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20190923_1442'),
    ]

    operations = [
        migrations.RunPython(update_teachers),
    ]
