# Generated by Django 2.1.5 on 2019-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20190923_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='can_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='can_book_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='can_pay',
            field=models.BooleanField(default=True),
        ),
    ]
