# Generated by Django 2.1.5 on 2019-10-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20191006_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='no_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='can_book',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='can_pay',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
