# Generated by Django 2.1.5 on 2019-10-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20191011_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teaching_venue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
