# Generated by Django 2.1.5 on 2019-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_class_teaching_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='address_country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
