# Generated by Django 2.1.5 on 2019-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_class_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='address_google',
            field=models.TextField(blank=True, null=True),
        ),
    ]
