# Generated by Django 2.1.5 on 2019-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_class_address_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alerts',
            field=models.BooleanField(default=False),
        ),
    ]
