# Generated by Django 2.1.5 on 2019-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_user_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_external_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_deactivated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
