# Generated by Django 2.1.5 on 2019-11-15 16:43

from django.db import migrations

def update_uc(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    UserCard = apps.get_model('main', 'UserCard')
    for x in UserCard.objects.all():
        if x.customer_id:
            # disable test records
            x.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20191112_1135'),
    ]

    operations = [
        migrations.RunPython(update_uc),
    ]
