# Generated by Django 2.1.5 on 2019-11-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20191122_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateenroll',
            name='secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
