# Generated by Django 2.1.5 on 2019-11-15 16:43

from django.db import migrations
import math

def backward(apps, schema_editor):
    pass


def update_classes(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('main', 'Class')
    for x in Class.objects.filter(is_private=True):
        x.custom_packages = []
        if x.rate and x.private_lesson_length and x.private_number_of_lessons:
            # disable test records
            key = 1
            for l in x.private_lesson_length:
                for n in x.private_number_of_lessons:
                    n = float(n)
                    l = float(l)
                    if l % 60:
                        minutes = "{} minutes".format(round(l % 60))
                    else:
                        minutes = ""
                    if math.floor(l / 60):
                        hours = "{} hour{}".format(math.floor(l / 60), "s" if math.floor(l / 60) > 1 else "")
                    else:
                        hours = ""
                    time_text = hours + ", " + minutes if hours and minutes else hours + minutes
                    converted = {
                        "isPrivate": True,
                        "description": '',
                        "currency": x.currency,
                        "totalPrice": round(l*n/60*float(x.rate)),
                        "numberOfLessons": round(n),
                        "perLesson": round(l/60*float(x.rate)),
                        "lessonLength": {
                            "value": round(l),
                            "text": time_text
                        },
                        "isPricePerPerson": False,
                        "minPersons": 1,
                        "maxPersons": 1,
                        "key": key,
                    }
                    key += 1
                    x.custom_packages.append(converted)
                    #print(x.pk, converted)
            x.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_teacherprofilelog'),
    ]

    operations = [
        migrations.RunPython(update_classes, backward),

    ]
