# Generated by Django 2.2.7 on 2019-12-20 17:12

from django.db import migrations


def delete_test_accs(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    User = apps.get_model('main', 'User')
    for x in User.objects.filter(stripe_account_id__isnull=False):
        if not x.has_external_account:
            x.stripe_account_id = None
            x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_newsletter'),
    ]

    operations = [
        migrations.RunPython(delete_test_accs),
    ]
