# Generated by Django 2.2.7 on 2019-12-24 13:53

from django.db import migrations

def update_learner_needs(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    ClassLearner = apps.get_model('main', 'ClassLearner')
    for x in ClassLearner.objects.all():
        if not x.learnerNeeds and x.data.get('learnerNeeds'):
            x.learnerNeeds = x.data.get('learnerNeeds')
            x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20191220_1712'),
    ]

    operations = [
        migrations.RunPython(update_learner_needs),
    ]
