# Generated by Django 2.2.7 on 2019-12-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20191224_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='paid_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
