# Generated by Django 2.2.7 on 2019-12-30 13:27

from django.db import migrations

def update_reserved_lessons(self):
    if self.klass.is_private:
        self.reserved_lessons = self.privateenroll_set.exclude(status='rejected').count()
    else:
        self.reserved_lessons = self.groupenroll_set.exclude(status='rejected').count()
    # funds are ready for release
    if self.reserved_lessons and not self.no_pay and not self.paid_status:
        self.paid_status = 1
    self.save()

def update_orders(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    ClassLearner = apps.get_model('main', 'ClassLearner')
    for x in ClassLearner.objects.all():
        update_reserved_lessons(x)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_classlearner_paid_status'),
    ]

    operations = [
        migrations.RunPython(update_orders),
    ]
