# Generated by Django 2.2.7 on 2020-01-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20191230_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_price_hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
