# Generated by Django 2.2.7 on 2020-01-22 13:07

import os, json
from django.db import migrations

def update_classes(apps, schema_editor):
    Class = apps.get_model('main', 'Class')
    for c in Class.objects.filter(class_type='other', lat=None, lng=None):
        try:
            addr = "St. Petersburg, FL"
            f = {
                'key' : os.environ['GOOGLE_MAPS_API_KEY'],
                'address' : addr,
            }

            api_url = "https://maps.googleapis.com/maps/api/geocode/json?%s" % urllib.parse.urlencode(f)

            with urllib.request.urlopen(api_url) as url:
                x = json.loads(url.read().decode())
                lat = x['results'][0]['geometry']['location']['lat']
                lng = x['results'][0]['geometry']['location']['lng']

                c.lat = lat
                c.lng = lng
                c.address_city = 'St. Petersburg'
                c.address_state = 'FL'
                c.save()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_class_is_price_hidden'),
    ]

    operations = [
        migrations.RunPython(update_classes),
    ]
