# Generated by Django 2.2.7 on 2020-01-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20200122_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='amount_full',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
