# Generated by Django 2.2.7 on 2020-01-31 14:30

from django.db import migrations

def update_orders(apps, schema_editor):
    ClassLearner = apps.get_model('main', 'ClassLearner')
    for c in ClassLearner.objects.filter():
        c.amount_full = c.amount
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_classlearner_amount_full'),
    ]

    operations = [
        migrations.RunPython(update_orders),
    ]
