# Generated by Django 2.2.7 on 2020-02-11 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20200131_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_classes', models.IntegerField()),
                ('is_monthly', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
