# Generated by Django 2.2.7 on 2020-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_boostmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostmembership',
            name='stripe_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
