# Generated by Django 2.2.7 on 2020-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_boostmembership_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostmembership',
            name='status',
            field=models.TextField(default=None),
        ),
    ]
