# Generated by Django 2.2.7 on 2020-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_boostmembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_boosted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
