# Generated by Django 2.2.7 on 2020-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_class_is_boosted'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='boost_weekday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
