# Generated by Django 2.2.7 on 2020-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_class_boost_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostmembership',
            name='option_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
