# Generated by Django 2.2.7 on 2020-03-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_boostmembership_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_classes', models.IntegerField()),
                ('is_monthly', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default=None)),
                ('stripe_id', models.TextField()),
                ('option_id', models.IntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_boosted_classes', to='main.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_boosted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
