# Generated by Django 2.2.7 on 2020-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_emailboost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostmembership',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
