# Generated by Django 2.2.7 on 2020-03-04 13:56

from django.db import migrations

def update_boost_orders(apps, schema_editor):

    OPTIONS = [
        {'id': 1, 'num_classes': 5, 'is_monthly': True, 'amount': 48, 'name': 'Solo'},
        {'id': 2, 'num_classes': 10, 'is_monthly': True, 'amount': 75, 'name': 'Academy'},
        {'id': 3, 'num_classes': 25, 'is_monthly': True, 'amount': 175, 'name': 'University'},
        {'id': 4, 'num_classes': 1, 'is_monthly': False, 'amount': 99, 'name': 'Single'},
    ]

    BoostMembership = apps.get_model('main', 'BoostMembership')
    for c in BoostMembership.objects.filter():
        op_id = c.option_id
        if not op_id:
            op_id = 1
        c.name = OPTIONS[op_id-1]['name']
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_boostmembership_name'),
    ]

    operations = [
        migrations.RunPython(update_boost_orders),
    ]

