# Generated by Django 2.2.7 on 2020-03-18 12:03

from django.db import migrations
from django.conf import settings
import PIL, os
from PIL import Image

def save_thumbnail(self, size=300):
    maxsize = (size, size)
    image = Image.open(self.class_media)
    image.thumbnail(maxsize, PIL.Image.ANTIALIAS)
    file, ext = os.path.splitext(self.class_media.name)
    if ext.startswith('.'):
        ext = ext[1:]
    if not ext:
        ext = 'png'
    image_path = os.path.join(settings.MEDIA_ROOT, file + ".thumbnail%s.%s" % (size, ext))
    image.save(image_path)

def update_media(apps, schema_editor):
    ClassMedia = apps.get_model('main', 'ClassMedia')
    maxsize = (300, 300)
    for c in ClassMedia.objects.all():
        save_thumbnail(c)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_auto_20200304_1356'),
    ]

    operations = [
        migrations.RunPython(update_media),
    ]
