# Generated by Django 2.2.7 on 2020-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_auto_20200324_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('multiple_dates', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('companies', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='uploads/events/')),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
