# Generated by Django 2.2.7 on 2020-04-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_auto_20200416_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlearner',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
