# Generated by Django 2.2.7 on 2020-04-30 18:04

from django.db import migrations


def update_user(apps, schema_editor):
    User = apps.get_model('main', 'User')
    Class = apps.get_model('main', 'Class')
    for u in User.objects.all():
        c = Class.objects.filter(teacher__user=u)
        if c and c[0].timezone:
            u.timezone = c[0].timezone
        else:
            u.timezone = 'America/Mazatlan'
        u.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_auto_20200429_1127'),
    ]

    operations = [
        migrations.RunPython(update_user),
    ]
