# Generated by Django 2.2.7 on 2020-05-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_auto_20200430_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='interval',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classlearner',
            name='interval_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classlearner',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
