# Generated by Django 2.2.7 on 2020-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20200501_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='current_period_end',
            field=models.IntegerField(null=True),
        ),
    ]
