# Generated by Django 2.2.7 on 2020-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_classlearner_current_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='current_period_start',
            field=models.IntegerField(null=True),
        ),
    ]
