# Generated by Django 2.2.7 on 2020-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_classlearner_current_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
