# Generated by Django 2.2.7 on 2020-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_auto_20200503_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
    ]
