# Generated by Django 2.2.7 on 2020-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_classlearner_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='payments',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classlearner',
            name='ready_pay',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='classlearner',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
