# Generated by Django 2.2.7 on 2020-05-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_auto_20200508_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlearner',
            name='payments',
        ),
    ]
