# Generated by Django 2.2.7 on 2020-05-08 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_remove_classlearner_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='payments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
