# Generated by Django 2.2.7 on 2020-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_classlearner_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlearner',
            name='num_lessons_per_interval',
            field=models.IntegerField(null=True),
        ),
    ]
