# Generated by Django 2.2.7 on 2020-05-16 17:11

from django.db import migrations



def update_orders(apps, schema_editor):
    ClassLearner = apps.get_model('main', 'ClassLearner')
    for c in ClassLearner.objects.filter(is_subscription=True):
        c.num_lessons_per_interval = c.num_lessons
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_classlearner_num_lessons_per_interval'),
    ]

    operations = [
        migrations.RunPython(update_orders)
    ]
