# Generated by Django 2.2.7 on 2020-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_auto_20200516_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostmembership',
            name='stripe_id',
            field=models.TextField(null=True),
        ),
    ]
