# Generated by Django 2.2.7 on 2020-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_auto_20200518_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_earn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
