# Generated by Django 2.2.7 on 2020-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_user_first_earn_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('metatag', models.TextField()),
            ],
        ),
    ]
