# Generated by Django 2.2.7 on 2020-06-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_metatag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('allow_contact', models.BooleanField()),
                ('teacher_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.Teacher')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
