# Generated by Django 2.2.7 on 2020-06-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_auto_20200625_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
