# Generated by Django 2.2.7 on 2020-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_user_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_paid_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
