# Generated by Django 2.2.7 on 2020-08-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_class_is_paid_by_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='is_paid_by_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
