# Generated by Django 2.2.7 on 2020-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_auto_20200820_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='is_paid_by_teacher',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
