# Generated by Django 2.2.7 on 2020-09-03 11:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_auto_20200827_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentByTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('single_class', models.IntegerField(blank=True, null=True)),
                ('classes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
        ),
    ]
