# Generated by Django 2.2.7 on 2020-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_paymentbyteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbyteacher',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
