# Generated by Django 2.2.7 on 2020-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_paymentbyteacher_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='activated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
