# Generated by Django 2.2.7 on 2020-09-04 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_class_activated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbyteacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
