# Generated by Django 2.2.7 on 2020-09-15 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0142_paymentbyteacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='boost_option_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChargeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.TextField()),
                ('amount', models.IntegerField()),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
