# Generated by Django 2.2.7 on 2020-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0143_auto_20200915_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
    ]
