# Generated by Django 2.2.7 on 2020-09-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0144_auto_20200916_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='show_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='show_phone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
