# Generated by Django 2.2.7 on 2020-09-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0146_addstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='replace_logo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
