# Generated by Django 2.2.7 on 2020-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0149_auto_20201012_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='show_phone_rule',
            field=models.CharField(choices=[('text', 'text'), ('call', 'call')], default='text', max_length=32),
        ),
    ]
