# Generated by Django 2.2.7 on 2021-01-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0150_class_show_phone_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='main_media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
