# Generated by Django 2.2.7 on 2021-01-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_companyprofile_main_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_free_member',
            field=models.BooleanField(default=False),
        ),
    ]
