# Generated by Django 2.2.7 on 2021-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0154_auto_20210315_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
