# Generated by Django 2.2.7 on 2021-04-12 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_companyprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
