# Generated by Django 2.2.7 on 2021-04-12 09:20

from django.db import migrations
import re
import uuid

used = {}

def gen_slug(apps, schema_editor):
    CompanyProfile = apps.get_model('main', 'companyprofile')
    rspace = re.compile('\s+')
    rother = re.compile('[^a-zA-Z0-9\.\-_]+')
    for row in CompanyProfile.objects.all():
        res = rspace.sub('-', row.name or str(uuid.uuid4()))
        row.slug = rother.sub('', res)
        if used.get(row.slug):
            row.slug = str(uuid.uuid4())
        used[row.slug] = True
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0156_companyprofile_slug'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]