# Generated by Django 2.2.7 on 2021-06-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_auto_20210412_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='reminder_10min',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='reminder_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='reminder_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='reminder_10min',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='reminder_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='reminder_renew',
            field=models.BooleanField(default=True),
        ),
    ]
