# Generated by Django 2.2.7 on 2021-07-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_auto_20210621_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='home_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='member_center_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
