# Generated by Django 2.2.7 on 2021-08-16 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0160_auto_20210719_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.TextField()),
                ('entity_id', models.IntegerField()),
                ('currency', models.TextField(blank=True, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('students', models.ManyToManyField(related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='entity'),
        ),
    ]
