# Generated by Django 2.2.7 on 2021-08-16 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_auto_20210816_1125'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='entity_type',
        ),
        migrations.AddField(
            model_name='membership',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
