# Generated by Django 2.2.7 on 2021-08-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_auto_20210816_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='owner',
            new_name='owner_user',
        ),
    ]
