# Generated by Django 2.2.7 on 2021-09-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0163_auto_20210823_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
