# Generated by Django 2.2.7 on 2021-09-05 20:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_membership_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='students',
        ),
        migrations.CreateModel(
            name='MembershipStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(blank=True, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.TextField(null=True)),
                ('status', models.CharField(default='wait_payment', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_full', models.DecimalField(decimal_places=2, max_digits=6)),
                ('end_at', models.DateTimeField(null=True)),
                ('current_period_start', models.IntegerField(null=True)),
                ('current_period_end', models.IntegerField(null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('payments', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.Membership')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
