# Generated by Django 2.2.7 on 2021-09-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0165_auto_20210905_2006'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membershipstudent',
            constraint=models.UniqueConstraint(fields=('student', 'membership'), name='user_membership'),
        ),
    ]
