# Generated by Django 2.2.7 on 2021-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_auto_20210906_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipstudent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
