# Generated by Django 2.2.7 on 2021-09-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0167_membershipstudent_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipstudent',
            name='user_membership',
        ),
        migrations.AddConstraint(
            model_name='membershipstudent',
            constraint=models.UniqueConstraint(fields=('student', 'membership', 'created_at'), name='user_membership'),
        ),
    ]
