# Generated by Django 2.2.7 on 2021-09-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0168_auto_20210906_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
