# Generated by Django 2.2.7 on 2021-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0169_membership_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='member_access_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
