# Generated by Django 2.2.7 on 2021-12-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0170_companyprofile_member_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_premium_community',
            field=models.BooleanField(default=False),
        ),
    ]
