# Generated by Django 2.2.7 on 2021-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0171_class_is_premium_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='belongs_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
