# Generated by Django 2.2.7 on 2022-02-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0172_user_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
