# Generated by Django 2.2.7 on 2022-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0173_auto_20220217_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='yearly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='period',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='yearly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
