# Generated by Django 2.2.7 on 2022-03-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0174_auto_20220228_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
