# Generated by Django 2.2.7 on 2022-05-17 16:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0175_user_notes2'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipstudent',
            name='invoices',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
