# Generated by Django 2.2.7 on 2022-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0176_membershipstudent_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='zoom_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
