# Generated by Django 2.2.7 on 2022-11-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0177_class_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about_us_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
