# Generated by Django 2.2.7 on 2023-04-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0178_companyprofile_about_us_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='customInterestsField',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='customLevelsField',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='customSkillsField',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='isAboutAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isAboutRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isChatEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isCityAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isCityRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isDMEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isDirectoryEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isDocumentAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isDocumentRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isEmailAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isEmailRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isPhoneAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isPhoneRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isProjectsAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isProjectsRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isSocialAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isSocialRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isTitleAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isTitleRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isUploadAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='isUploadRequired',
            field=models.BooleanField(default=False),
        ),
    ]
