# Generated by Django 2.2.7 on 2023-04-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0179_auto_20230406_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='isAboutAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isAboutRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isChatEnabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isCityAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isCityRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isDMEnabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isDirectoryEnabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isDocumentAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isDocumentRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isEmailAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isEmailRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isPhoneAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isPhoneRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isProjectsAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isProjectsRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isSocialAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isSocialRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isTitleAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isTitleRequired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isUploadAllowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isUploadRequired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
