# Generated by Django 2.2.7 on 2023-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0180_auto_20230406_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipstudent',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
