# Generated by Django 3.2.19 on 2023-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0182_auto_20230531_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipstudent',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='social',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipstudent',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
