# Generated by Django 3.2.19 on 2023-06-08 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0185_comment_is_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='top_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='type',
            field=models.CharField(choices=[('C', 'COMMUNITY'), ('E', 'EVENT'), ('T', 'TOPIC')], default='C', max_length=100),
        ),
        migrations.AddField(
            model_name='discussion',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
