# Generated by Django 3.2.20 on 2023-07-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0183_auto_20230612_1006'),
        ('main', '0186_auto_20230608_1135'),
    ]

    operations = [
    ]
