# Generated by Django 3.2.20 on 2023-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0187_merge_0183_auto_20230612_1006_0186_auto_20230608_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/chat/'),
        ),
    ]
