# Generated by Django 3.2.20 on 2023-08-01 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0188_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='block_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
