# Generated by Django 3.2.20 on 2023-08-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0189_discussion_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
