# Generated by Django 3.2.20 on 2023-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0190_comment_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
